Repository bhumikatewary/Practice-Problems, pull requests merged in 2022-10, with the labels that each got.

#11 Create roman_numerals_to_int.py
  Math/armstrong.py
  Strings/roman_numerals_to_int.py
Labels: create issue

#20 Data Structures Full Notes
  Data Structures Full Notes
Labels: hactoberfest

#45 Craeted SmallestAndLargestElementSinglyLL.java
  LinkedList/SmallestAndLargestElementSinglyLL.java
Labels: hactoberfest

#58 Fixes #53
  Stacks/Java/StackUsingLinkedList.java
Labels: hactoberfest

#61 Added a array question in C++
  Arrays/C++/Maximum_Sum_Of_An_Hourglass.cpp
Labels: hactoberfest

#62 Intersection of Two Sorted Linked Lists
  LinkedList/C++/intersectionofLinkedLists.cpp
Labels: hactoberfest

#65 Searching in python
  Searching/Python/Iterative_binary_search.py
  Searching/Python/Iterative_linear_search.py
  Searching/Python/Recursive_binary_search.py
  Searching/Python/Recursive_linear_search.py
Labels: hactoberfest

#64 Fixes #57
  Trees/Java/BinaryTree.java
Labels: hactoberfest

#70 added DSU
  DSU/implentation_of_dsu.cpp
Labels: hactoberfest

#67 Adding Lomuto Partion Algorithm
  Sorting/Lomuto Partition.cpp
Labels: hactoberfest

#60 Pancake Sort in Java
  Arrays/Java/Pancake.java
Labels: hactoberfest

#84 Created another Linked list problem solution file ReverseLL.java
  LinkedList/Java/ReverseLL.java
Labels: hactoberfest

#81 Intersection of Arrays
  Arrays/C++/Intersection of An Array.cpp
Labels: hactoberfest

#80 Reversing first k elements of a queue
  Queues/C++/ReversingKelements.cpp
  Queues/C++/ReversingKelements.exe
Labels: hactoberfest

#55 Added Expression Tree Implementation
  Trees/C/Expression_tree/BST.c
  Trees/C/Expression_tree/BST.h
  Trees/C/Expression_tree/Makefile
  Trees/C/Expression_tree/Stack.c
  Trees/C/Expression_tree/Stack.h
  Trees/C/Expression_tree/main.c
  Trees/C/Expression_tree/problem_statement.txt
Labels: hactoberfest

#59 added linkedlist files for python
  LinkedList/Python/deletion.py
  LinkedList/Python/insertion.py
  LinkedList/Python/traversal.py
Labels: hactoberfest

#75 added code for GCD and LCM in math problem
  Math/C++/GCDandLCM.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#89 Add Binary tree maximum path sum, Add gitignore file
  .gitignore
  Trees/C++/binary_tree_maximum_path_sum.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#72 Linked List Deletion
  LinkedList/C/linkedlist_deletion.c
Labels: hacktoberfest, hacktoberfest-accepted

#24 Added a Readme file for the Array problems to enable better navigation
  Arrays/C++/README.md
Labels: hacktoberfest, hacktoberfest-accepted

#91 Detect loop in linked list uploaded
  hackotberfest.cpp
  tree_algorithms/BFS&DFS_traversal.cpp
  tree_algorithms/Height_of_BT.cpp
  tree_algorithms/Left_view_&_Right_view.cpp
  tree_algorithms/boundary_traversal.cpp
  tree_algorithms/diameter_of_BT.cpp
  tree_algorithms/minimum_time_to_burn.cpp
  tree_algorithms/root_leaf_sum.cpp
  tree_algorithms/zig_zag_traversal.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#114 Added Intersection of Two Linked Lists Problem in Java
  LinkedList/Java/Intersection of Two Linked Lists.java
Labels: hacktoberfest, hacktoberfest-accepted

#130 Create reverserecursion.cpp
  Recursion/C++/reverserecursion.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#105 Added Strongly Connectec Components of a Graph
  Graph/C++/SCC.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#128 Added Find next Smaller of next Greater in an array Problem in C++
  Arrays/C++/Find next Smaller of next Greater in an array.cpp
  Arrays/C++/Rotate Array.cpp
  Arrays/C++/Search a 2D Matrix.cpp
  DP/C++/Climbing Stars.cpp
  DP/Java/Frog Jump.java
  DP/Java/Longest Common Subsequence.java
  Trees/C++/Maximum Depth of Binary Tree.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#116 Added Rotate Array Problem in C++
  Arrays/C++/Rotate Array.cpp
Labels: hacktoberfest

#125 Added Flood Fill Problem in C++
  Graph/C++/Flood Fill.cpp
  Graph/C++/Is Graph Bipartite.cpp
  Graph/C++/Surrounded Regions.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#120 Added Surrounded Regions Problem in C++
  Graph/C++/Surrounded Regions.cpp
Labels: hacktoberfest

#113 added recursive,iterative searching in linkedlist
  LinkedList/C++/linkedlistsearch.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#108 Create rabbit_in_forest.cpp
  Arrays/C++/rabbit_in_forest.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#107 Added Articulation Point Issue Number 46
  Graph/C++/Articulation Points.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#106 Added Kruskal Minimum Spanning Tree for a graph
  Graph/C++/Krushkal's MST.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#92 Create FindMissingPositive.java
  Arrays/Java/FindMissingPositive.java
Labels: hacktoberfest, hacktoberfest-accepted

#94 Create detect-cycle.cpp
  LinkedList/C++/detect-cycle.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#118 Added the program Arithmetic Slices (Using DP)
  DP/C++/Arithmetic_Slices.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#126 Issue #102 FirstMissingInteger.py
  Arrays/Python/FirstMissingInteger.py
Labels: hacktoberfest, hacktoberfest-accepted

#131 Create Rat_in_a_maze.cpp
  Recursion/C++/Rat_in_a_maze.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#137 Added Number of Enclaves Problem in C++
  Graph/C++/Number of Enclaves.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#140 Added Circle of string problem in graph
  DP/C++/0 - 1 Knapsack Problem.cpp
  DP/C++/Egg drop problem.cpp
  Graph/C++/Circle of strings.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#145 added dijkstra problem statement, input and output
  Graph/C++/Dijkstra.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#146 added 3sat problem statement, solution and output
  Graph/C++/3 SAT.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#148 Added Number of Provinces problem in C++
  Graph/C++/Number of Provinces problem.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#149 Added Search a 2D Matrix Problem in Java
  Arrays/Java/Search a 2D Matrix.java
  DP/C++/Maximum Depth of Binary Tree.cpp
  Stacks/C++/Valid Parentheses.cpp
  Strings/C++/Count and Say.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#167 added bellman-ford algorithm with problem statement, code and output
  Graph/C++/Bellman-Ford algorithm.txt
Labels: hacktoberfest, hacktoberfest-accepted

#165 Connect n ropes with minimum cost using priority queue
  Queues/Java/ConnectRopes.java
Labels: hacktoberfest, hacktoberfest-accepted

#159 Add Increasing triplet subsequence problem
  DP/C++/IncreasingTripletSubsequence.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#156 Added Car Fleet II Problem in Java
  Arrays/C++/Repeat and Missing Number Array.cpp
  Arrays/C++/Set Matrix Zeroes.CPP
  Arrays/Java/Car Fleet II.java
  Arrays/Java/Minimize XOR.java
  Arrays/Java/Super Ugly Number.java
Labels: hacktoberfest, hacktoberfest-accepted

#153 Added Binary Tree Preorder Traversal Problem in C++
  Trees/C++/Binary Tree Preorder Traversal.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#164 Prefix to Postfix Problem solution using Stack added
  Stacks/Java/Prefix_to_Postfix.java
Labels: hacktoberfest, hacktoberfest-accepted

#163 Added Previous Smaller Element Algorithm
  Arrays/C++/Find Previous Smaller Element in Array.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#144 added 2SAT cpp
  Graph/C++/2 SAT.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#160 Added Depth First Search Algorithm
  Graph/C++/Depth First Search.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#161 Added Breadh First Search
  Graph/C++/Breadth First Search.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#162 Added Previous Greater Element Algorithm
  Arrays/C++/Find Previous Greater Element in Array.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#169 Allocate minimum number of pages problem in java
  Arrays/Java/AllocateMinimunPages.java
  Arrays/Java/InfiniteSortedArray.java
Labels: hacktoberfest, hacktoberfest-accepted

#172 Added Topological sort BFS Problem in Java
  Graph/Java/TopoLogicalSortBFS.java
Labels: hacktoberfest, hacktoberfest-accepted

#176 Added Merge Intervals problem in C++
  Greedy Algorithms/Merge Intervals.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#179 Added Kadane's Algorithm in Cpp
  Arrays/C++/Kadane.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#180 Added Dutch Algorithm
  Arrays/C++/Sort Array with Dutch Algo.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#216 Print matrix in spiral order in Java
  Arrays/Java/SpiralMatrix.java
Labels: hacktoberfest, hacktoberfest-accepted

#201 i have added some lines for code explanation
  Arrays/C++/Find Peak Element.cpp
  Arrays/C++/First Missing Integer.cpp
  Arrays/C++/Max Min.cpp
  Arrays/C++/Sort array with squares.cpp
  CSES/Bit Strings.cpp
  CSES/Coin Piles.cpp
  CSES/Distinct Numbers.cpp
  CSES/Increasing Array.cpp
  CSES/Missing Number.cpp
  CSES/Permutations.cpp
  CSES/Repetitions.cpp
  CSES/Tower of Hanoi.cpp
  CSES/Trailing Zeros.cpp
  CSES/Two Knights.cpp
  CSES/Weird Algorithm.cpp
  LinkedList/C/insertingAtHead.c
  LinkedList/C/insertingAtHead.exe
  LinkedList/C/insertionAtEnd.c
  Math/C++/FizzBuzz.cpp
  Math/C++/Palindrome Integer.cpp
  Math/C++/Reverse integer.cpp
  Math/C++/Trailing Zeros in Factorial.cpp
  OOPS/AddSub.cpp
  OOPS/AddSub.exe
  OOPS/BasicInheritance.cpp
  OOPS/ClassTemplate.cpp
  OOPS/ConsAndDesInheritance.cpp
  OOPS/Constructors.cpp
  OOPS/DynamicBinding.cpp
  OOPS/FunctionOverriding.cpp
  OOPS/MultilevelInheritance.cpp
  OOPS/MultipleInheritance.cpp
  OOPS/bookDetails.cpp
  Sorting/BubbleSort.cpp
  Sorting/BucketSort.cpp
  Sorting/ChocolateDistributionProblem.cpp
  Sorting/CountInversionsInArray.cpp
  Sorting/CycleSort.cpp
  Sorting/HeapSort.cpp
  Sorting/MinimumDifferenceInArray.cpp
  Sorting/NaivePartition.cpp
  Sorting/SortAnArrayWith3TypesOfElements.cpp
  Sorting/insertionSort.cpp
  Sorting/selectionSort.cpp
  Strings/C++/Palindrome String.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#181 Find All Permutations using STL
  Arrays/C++/AllPermute.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#183 added phase shift problem
  DP/C++/Phase Shift.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#202 Painter's partiton
  LinkedList/C++/delete_node.cpp
  LinkedList/C++/delete_node.exe
  Recursion/C++/Painters_partition.cpp
  painter's_partition.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#209 added short hand solution for python array missedSmallerInteger #83
  Arrays/Python/FirstMissingInteger.py
  CSES/README.md
  CSES/Weird Algorithm/Weird Algorithm.cpp
  CSES/Weird Algorithm/Weird Algorithm.py
Labels: hacktoberfest, hacktoberfest-accepted

#222 Delete Node in a Linked List
  LinkedList/Delete_Node_in_a_Linked_List.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#212 Adding new Program
  Arrays/C++/Median of Two Sorted array of different size.cpp
  Arrays/C++/README.md
Labels: hacktoberfest, hacktoberfest-accepted

#214 Adding new Program in Array/C++/
  Arrays/C++/Missing Number in Arithmetic Progression.cpp
  Arrays/Python/Smallest positive missing number in unsorted array.py
Labels: hacktoberfest, hacktoberfest-accepted

#218 Add sparse matrix representation
  Arrays/C++/SparseMatrixAddition.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#230 Added code for Transpose Matrix
  Arrays/Java/TransposeMatrix.java
Labels: hacktoberfest, hacktoberfest-accepted

#236 Find the nearest smallest element in the left side of an array using stack
  Stacks/Java/prevSmallerElement.java
Labels: hacktoberfest, hacktoberfest-accepted

#238 Add practice Problems
  DSU/most_stones_removed_with_same_row_or_colummn.cpp
  DSU/network_connections.cpp
  DSU/number_of_provinces.cpp
  DSU/redundant_connections.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#227 Pivot in the Array in C++.
  Arrays/C++/Pivot in the Array.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#235 Palindrome Flipping Solution : Codechef Starters 60 in java
  Strings/Java/Palindrome_Flipping.class
  Strings/Java/Palindrome_Flipping.java
Labels: hacktoberfest, hacktoberfest-accepted

#229 Longest Palindromic Substring
  Strings/C++/Longest_Palindrome_Substring.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#237 Create To count number of palindrome string.cpp
  Strings/C++/To count number of palindrome string.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#244 Rotten Oranges Problem in C++.
  Stacks/C++/Rotten Oranges problem.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#249 Changes made by akruti sarangi added new array python problem to project
  Arrays/Python/Modulo_strength.py
Labels: hacktoberfest, hacktoberfest-accepted

#242 Add PHP string examples
  Strings/PHP/php_implode.php
  Strings/PHP/php_substring.php
  Strings/PHP/php_trim.php
Labels: hacktoberfest

#247 Adding Matrix Multiplication
  Arrays/C++/Program to multiply two matrices.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#251 Implementation Of Queue.cpp
  Queues/C++/Implementation Of Queue.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#252 Update and rename new.py to Knapsack.py
  DP/Python/Knapsack.py
  DP/Python/new.py
Labels: hacktoberfest, hacktoberfest-accepted

#253 Update and rename new.python to valid_parenthesis.py
  Stacks/Python/new.python
  Stacks/Python/valid_parenthesis.py
Labels: hacktoberfest, hacktoberfest-accepted

#266 Create knapsack.cpp
  Greedy Algorithms/C++/knapsack.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#267 Create SO_Part2_Solution.cpp
  Strings/C++/SO_Part2_Solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#268 Create Sum of Diagonal Of Matrix.java
  Arrays/Java/Sum of Diagonal Of Matrix.java
Labels: hacktoberfest, hacktoberfest-accepted

#272 Book Management System
  Book Management System/bookstoresystem.cpp
  Book Management System/bookstoresystem.exe
Labels: hacktoberfest, hacktoberfest-accepted

#274 Create recursion.cpp
  Recursion/C++/recursion.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#270 Adding Spiral_Matrix.cpp #246
  Arrays/C++/Spiral_Matrix.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#256 Minimum Cost Spanning tree using greedy
  Greedy Algorithms/C++/Kruskal's algorithm.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#263 Find Nth Catalan Number
  DP/C++/NthCatalan.cpp
  LinkedList/C++/Checkpalindrome.cpp
  LinkedList/C++/MergeSortLL.cpp
  LinkedList/C++/MergesortedLL.cpp
  LinkedList/C++/RotateLL.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#277 Create pattern_printing.cpp
  Recursion/C++/pattern_printing.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#278 Create FindNUniqueIntegersSumuptoZero.java
  Arrays/Java/FindNUniqueIntegersSumuptoZero.java
Labels: hacktoberfest, hacktoberfest-accepted

#279 Create Number_Of_Islands.cpp
  Recursion/C++/Number_Of_Islands.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#280 Peak Index in a mountain array
  Arrays/Java/PeakIndex.java
Labels: hacktoberfest, hacktoberfest-accepted

#284 Create odd_occuring.cpp
  Bit Manipulation/C++/odd_occuring.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#276 Create Longest_Possible_Subs.cpp
  Strings/C++/Longest_Possible_Subs.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#286 Intersection of Two Array II
  Arrays/Java/Intersection.java
  Arrays/Java/Search2D.java
Labels: hacktoberfest, hacktoberfest-accepted

#288 Create Palindrome.java
  Strings/Java/Palindrome.java
Labels: hacktoberfest, hacktoberfest-accepted

#289 Create Multiplication.Java
  Arrays/Java/Multiplication.java
Labels: hacktoberfest, hacktoberfest-accepted

#290 Create pascals_triangles.java
  Arrays/Java/pascals_triangles.java
Labels: hacktoberfest, hacktoberfest-accepted

#285 right view of tree
  Trees/C++/rightview.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#287 Added Implementation of Djikstra 's algorithm
  Greedy Algorithms/C++/Djikstra_algorithm.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#299 added palindrome checker in javascript
  Strings/javascript/palindrome_checker.js
Labels: hacktoberfest, hacktoberfest-accepted

#300 added missing smallest positive integer problem solution in javascript
  Arrays/javascript/missingSmallestPositiveInteger.js
Labels: hacktoberfest, hacktoberfest-accepted

#291 Create 23_MergekSortedLists.java
  LinkedList/C++/23_MergekSortedLists.java
Labels: hacktoberfest, hacktoberfest-accepted

#296 Create SwappingNodes.cpp
  LinkedList/C++/SwappingNodes.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#308 Create BinarySearch.java
  Searching/Java/BinarySearch.java
Labels: hacktoberfest, hacktoberfest-accepted

#309 added number of palindrome word finder in python with one-liner solution
  Strings/Python/NumberOfPalindrome.py
Labels: hacktoberfest, hacktoberfest-accepted

#310 Heap Sort in Java
  Sorting/HeapSort.java
Labels: hacktoberfest, hacktoberfest-accepted

#311 Time convertor (12hour to 24hour)
  Strings/C++/12hour_to_24hour.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#323 Resolving issue #317
  Strings/C++/Rabin-Karp Algorithm for Pattern Searching.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#324 Resolving issue #318
  Strings/C++/Implementation of KMP pattern searching.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#325 Resolving issue #319
  Strings/C++/Naive Pattern searching.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#326 Resolving issue #320
  Strings/C++/Palindrome Partitioning.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#327 Resolving issue #312
  Strings/C++/First non-repeating character in the given String.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#338 Successfully added the program to check the number is happy or not
  Arrays/C++/Strassen_Multiplication.cpp
  Math/Python/Happy_number.py
  Strings/C++/Unique_string_lexicographically.cpp
  Strings/Python/String_Happy.py
Labels: hacktoberfest, hacktoberfest-accepted

#328 Added Print unique string Lexicographically program
  Strings/C++/Unique_string_lexicographically.cpp
Labels: hacktoberfest

#331 Added all proposed programs mentioned in #292
  DP/C++/SieveOfEratosthenes.cpp
  Graph/C++/TopologicalSort.cpp
  LinkedList/C++/deletionInCircularLinkedList.cpp
  Queues/C++/Queue_usingLinkedList.cpp
  Trees/C++/Deletion&InsertionInBST.cpp
  tree_algorithms/AVL_RotationInTree.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#329 Added Matrix Multiplication program (2*2) by Strassen Method
  Arrays/C++/Strassen_Multiplication.cpp
  Strings/C++/Unique_string_lexicographically.cpp
Labels: hacktoberfest, hacktoberfest-accepted
